Section how it works
CollyWolly9798/lazy-team pull request #12
Opened 2024-10-19 16:15 UTC by anastasiia-koc

2024-10-19 16:18 UTC, anastasiia-koc commented
Я анулювала в медіа правилі для дескопа падінг для контейнера, тому що він мені ламав верстку, не знаю як це пофіксити(

2024-10-20 09:46 UTC, CollyWolly9798 requested changes
потрбні щоб гумова верстка при 320 до 375,фонові кольори повинні розтягуватись повністю,замість width потрібно використовувати max-width

2024-10-20 18:57 UTC, anastasiia-koc commented
Я не зовсім розумію поняття гумової верстки, min-width I max-width
прописані для контейнера. А ще кольори в мене не розтягуються, бо вони
задані на div, а зазвичай background-color задається на секцію, так як в
мене в секції два різні кольори, то я не знаю як це реалізувати

нд, 20 жовт. 2024 р. о 10:47 Oleksandr Riabyi ***@***.***>
пише:

> ***@***.**** requested changes on this pull request.
>
> потрбні щоб гумова верстка при 320 до 375,фонові кольори повинні
> розтягуватись повністю,замість width потрібно використовувати max-width
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/CollyWolly9798/lazy-team/pull/12#pullrequestreview-2380307708>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BJ5KELZN6XQQI5V4K7O6QV3Z4N32BAVCNFSM6AAAAABQHTVELSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGOBQGMYDONZQHA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-10-20 19:45 UTC, anastasiia-koc commented
✅

Настя Коцюба додає реакцію в Gmail
<https://www.google.com/gmail/about/?utm_source=gmail-in-product&utm_medium=et&utm_campaign=emojireactionemail#app>

2024-10-21 05:24 UTC, CollyWolly9798 requested changes

2024-10-21 05:24 UTC, CollyWolly9798 commented on src/partials/how-it-works.html
> +            srcset="../img/how-it-works/woman-desktop.png, ../img/how-it-works/woman-desktop@2x.png"
шлях до зображення потрібно вказувати без двух крапок  на початку

2024-10-21 05:24 UTC, CollyWolly9798 commented on src/partials/how-it-works.html
> +        <h2 class="visually-hidden">How it works</h2>
додайте id="how-it-works"

2024-10-21 06:58 UTC, CollyWolly9798 approved these changes

2024-10-21 06:58 UTC, merged