hero fixed
CollyWolly9798/lazy-team pull request #13
Opened 2024-10-19 16:33 UTC by yelyzavetamedunytsia

2024-10-19 18:54 UTC, CollyWolly9798 requested changes
потрібно зробити гумову верстку з 320 до 375 і я запитав у ментора за фон,"Зелений фон повинен розтягуватись на всю ширину, а зображення ні, воно повинно мати максимальну оригінальну ширину."

2024-10-19 19:47 UTC, yelyzavetamedunytsia commented
ніби виправила 😅

2024-10-20 12:48 UTC, CollyWolly9798 commented
потрібно,щоб фон такоже тянувся і на мобільній версії і на планшетній в ширину

2024-10-20 14:07 UTC, yelyzavetamedunytsia commented
зробила ✅

2024-10-20 15:10 UTC, CollyWolly9798 approved these changes
гарна робота

2024-10-20 15:10 UTC, merged